resources:
  repositories:
    - repository: yaml-pipeline-templates
      type: git
      name: dx-yaml-pipeline-templates
      ref: master
    - repository: tools
      type: git
      name: CICD-new-world-tools
      ref: refs/heads/master
trigger:
  branches:
    include:
      - main
steps:
  - template: templates/build-template.yaml
