resources:
  repositories:
    - repository: yaml-pipeline-templates
      type: git
      name: dx-yaml-pipeline-templates
      ref: master
    - repository: tools
      type: git
      name: CICD-new-world-tools
      ref: refs/heads/master
trigger:
  branches:
    include:
      - alpha
steps:
  - template: templates/build-template.yaml
    parameters:
      versionScript: lerna:version:alpha
      publishScript: lerna:publish:alpha
      buildScript: nx:affected:build --base=alpha
      testScript: nx:affected:test:cc --base=alpha
      lintScript: nx:affected:lint --base=alpha
      releaseBranch: alpha
