resources:
  repositories:
    - repository: yaml-pipeline-templates
      type: git
      name: dx-yaml-pipeline-templates
      ref: master
    - repository: tools
      type: git
      name: CICD-new-world-tools
      ref: refs/heads/master
trigger:
  branches:
    include:
    - beta
steps:
  - template: templates/build-template.yaml
    parameters:
      versionScript: lerna:version:beta
      publishScript: lerna:publish:beta
      buildScript: build:beta
      releaseBranch: beta
